spring:
  datasource:
    url: jdbc:h2:file:./data/telegram-bot-dev
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
tg:
  bot:
    token: 8265732417:AAGuOyZBygAe8Tl3aAVDRnXFXqhEnpEPu3Y
  chat:
    id: 153318601