spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: demo

railway:
  xsrf:
    token: 783fd7d7-d725-4d9f-b670-65f09dec3301
  cookie: _ga=GA1.1...; other cookies...